name: luna

services:
  db:
    image: ankane/pgvector
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: luna
    ports:
      - "5432:5432"